server:
  port: 18080

spring:
  application:
    name: gateway-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用通过服务名动态路由
          lower-case-service-id: true  # 服务名转为小写
      routes:
        - id: user-service-route
          uri: lb://consumer-eureka-service  # lb:// 表示负载均衡
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=0  # 去掉路径前缀（如 /api）

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    lease-expiration-duration-in-seconds: 60
    metadata-map:
      system: GVC


management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: info,health,gateway